### PR TITLE
Add helpers for Table Storage SAS token

### PR DESCRIPTION
**Pull request by nickmhankins**
This is a prerequisite for a PR in the azurerm provider:
terraform-providers/terraform-provider-azurerm#7770

Reference issue: 
terraform-providers/terraform-provider-azurerm#7769

### CODE REVIEW

**Comment by nickmhankins** [comment]
Signed the CLA last week but still shows pending...

**Comment by nickmhankins** [comment]
@tombuildsstuff @katbyte Can you guys help me out here?  CLA still stuck in pending.

**Comment by nickmhankins** [comment]
@tombuildsstuff @katbyte @mbfrahry Anyone available to check this out?  It's been quite some time.

**Comment by katbyte** [comment]
Hey @nickmhankins - i took a look at this today, and after some internal discussion some concerns were raised on that it created a SAS token for a specific API version - and these tokens can change from version to version and the consumer needs to be aware of this a user needs to ensure compatibility. Thus there was some hesitancy in moving forward with this PR (and a consideration the existing token functions should be deprecated.

What is the use case you are trying to solve here? and would MSI work instead?

**Comment by nickmhankins** [comment]
Hi, sorry I no longer work the company that needed this, closing

**Pull request closed without merging**
