### PR TITLE
SP certificate validation validates passphrase but ignore file extension

### PR DESCRIPTION
**Pull request by magodo**
SP certificate validation now don't necessarily requires the file to end with `.pfx` (fixes: terraform-providers/terraform-provider-azurerm#8250), but do validates the passphrase.

Besides, I added all the files in *testdata*, including those unnecessary ones (the private key, crt, csr), please feel free to remove them if not needed here.

### CODE REVIEW

**Comment by bnfbiz** [comment]
@magodo when can this be approved and merged into for release?

**Comment by magodo** [comment]
Hey @katbyte would you mind taking a look at this PR?

**Comment by bnfbiz** [comment]
@magodo  and @katbyte any update on this?

**Comment by bnfbiz** [comment]
@magodo  and @katbyte any update on this?

**Comment by bnfbiz** [comment]
@magodo  and @katbyte any update on this?  when will it be merged?  Thanks!

**Review by tombuildsstuff — APPROVED** [review]
LGTM 👍

**Pull request merged**
