### PR TITLE
Update Hamilton

### PR DESCRIPTION
**Pull request by manicminer**
Depends on: https://github.com/manicminer/hamilton/pull/154 and https://github.com/manicminer/hamilton-autorest/pull/1 ~(requires rebase)~

- Updates hamilton to v0.43.0 and introduces hamilton-autorest v0.2.0

### CODE REVIEW

**Review by katbyte — APPROVED** [review]
LGTM 🌿

**Comment by manicminer** [comment]
@katbyte I made changes which I think warrant another look if you can, thanks!

**Comment by manicminer** [comment]
Tested with terraform-provider-azurerm v3.0.2

**Review by katbyte — APPROVED** [review]
LGTM 🥫

**Pull request merged**
